"""empty message

Revision ID: a1f8d43bf110
Revises: 14ba97d70170
Create Date: 2020-05-12 00:09:56.391791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f8d43bf110'
down_revision = '14ba97d70170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed=False where completed IS NULL;')
    op.alter_column('todos','completed',nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
